from __future__ import annotations


ISSUE_EXPLANATIONS: dict[str, dict[str, str]] = {
    "graph.cycle": {
        "title": "Reference cycle",
        "severity": "warning",
        "description": "A directed reference path loops back to an earlier record.",
        "resolution": "Break the cycle by removing or changing one reference edge.",
    },
    "graph.orphan": {
        "title": "Orphan record",
        "severity": "warning",
        "description": "A non-product, non-schema record has no incoming or outgoing graph references.",
        "resolution": "Reference the record from a product or another record, or remove it.",
    },
    "lint.description.missing": {
        "title": "Missing description",
        "severity": "warning",
        "description": "A record should include a useful human-readable description.",
        "resolution": "Add a non-empty description field.",
    },
    "lint.owner.placeholder": {
        "title": "Placeholder owner",
        "severity": "warning",
        "description": "The owner field uses a placeholder value.",
        "resolution": "Set owner to the team, person, or system responsible for the record.",
    },
    "lint.status.draft": {
        "title": "Draft record",
        "severity": "warning",
        "description": "Draft records are not considered release-ready.",
        "resolution": "Move the record to review or ready once the contract is accepted.",
    },
    "pack.unknown": {
        "title": "Unknown pack",
        "severity": "error",
        "description": "The requested pack ID is not available.",
        "resolution": "Run `verity pack list` and use one of the listed pack IDs.",
    },
    "pack.discovery.invalid": {
        "title": "Pack discovery failed",
        "severity": "error",
        "description": "A local or installed pack source could not be resolved into a valid pack manifest.",
        "resolution": "Check local pack paths and installed `verityspec.packs` entry points, then rerun `verity pack list`.",
    },
    "pack.external.builtin_collision": {
        "title": "External pack shadows built-in pack",
        "severity": "error",
        "description": "A local pack path declares a pack ID that is reserved by a built-in pack.",
        "resolution": "Use a distinct external pack ID. Built-in pack IDs cannot be shadowed by local pack paths.",
    },
    "pack.external.duplicate_id": {
        "title": "Duplicate external pack ID",
        "severity": "error",
        "description": "Multiple local pack paths declare the same pack ID.",
        "resolution": "Remove the duplicate local path or ensure each external pack has a distinct ID.",
    },
    "pack.external.manifest_id_missing": {
        "title": "External pack manifest missing ID",
        "severity": "error",
        "description": "A local pack manifest does not declare a string `id` field.",
        "resolution": "Add a string `id` field to the pack manifest.",
    },
    "pack.external.manifest_invalid": {
        "title": "External pack manifest invalid",
        "severity": "error",
        "description": "A local pack manifest could not be parsed as a JSON object.",
        "resolution": "Fix the local pack's `pack.json` file and rerun `verity pack doctor`.",
    },
    "pack.external.missing_manifest": {
        "title": "External pack manifest missing",
        "severity": "error",
        "description": "A local pack path does not contain a `pack.json` manifest.",
        "resolution": "Point the path at a pack directory or `pack.json` file.",
    },
    "pack.external.overrides_installed": {
        "title": "External pack overrides installed pack",
        "severity": "warning",
        "description": "A local pack path supplies the same pack ID as an installed package entry point and takes precedence.",
        "resolution": "Confirm that the local override is intentional, or remove the local path to use the installed pack.",
    },
    "pack.external.path_invalid": {
        "title": "External pack path invalid",
        "severity": "error",
        "description": "A local pack path could not be resolved.",
        "resolution": "Fix the local path or remove the invalid `packPaths`, `--pack-path`, or `verity pack --path` entry.",
    },
    "pack.installed.builtin_collision": {
        "title": "Installed pack shadows built-in pack",
        "severity": "error",
        "description": "An installed pack entry point declares a pack ID that is reserved by a built-in pack.",
        "resolution": "Rename or uninstall the package. Built-in pack IDs cannot be shadowed by installed packs.",
    },
    "pack.installed.duplicate_id": {
        "title": "Duplicate installed pack ID",
        "severity": "error",
        "description": "Multiple installed entry points declare the same pack ID.",
        "resolution": "Keep only one installed distribution for that pack ID, or make the duplicate package expose a distinct ID.",
    },
    "pack.installed.entry_point_load_failed": {
        "title": "Installed pack entry point failed",
        "severity": "error",
        "description": "An installed `verityspec.packs` entry point could not be imported or called.",
        "resolution": "Fix or uninstall the package exposing the failing entry point, then rerun `verity pack doctor`.",
    },
    "pack.installed.entry_point_name_mismatch": {
        "title": "Installed pack entry point name mismatch",
        "severity": "error",
        "description": "An installed entry-point name does not match the resolved pack manifest ID.",
        "resolution": "Update the package entry point name so it exactly matches the manifest `id`.",
    },
    "pack.installed.manifest_id_missing": {
        "title": "Installed pack manifest missing ID",
        "severity": "error",
        "description": "An installed pack manifest does not declare a string `id` field.",
        "resolution": "Fix the installed package manifest so it declares a string `id`.",
    },
    "pack.installed.manifest_invalid": {
        "title": "Installed pack manifest invalid",
        "severity": "error",
        "description": "An installed pack manifest could not be parsed as a JSON object.",
        "resolution": "Fix or uninstall the package exposing the invalid manifest.",
    },
    "pack.installed.missing_manifest": {
        "title": "Installed pack manifest missing",
        "severity": "error",
        "description": "An installed pack entry point resolved to a path without a `pack.json` manifest.",
        "resolution": "Fix the entry point so it returns a pack directory or `pack.json` path.",
    },
    "profile.required_pack": {
        "title": "Required profile pack missing",
        "severity": "error",
        "description": "The selected product-contract profile requires a pack that is not loaded by the workspace.",
        "resolution": "Add the required pack to the workspace, or use a profile that matches the workspace scope.",
    },
    "profile.required_record_kind": {
        "title": "Required profile record kind missing",
        "severity": "error",
        "description": "The selected product-contract profile requires at least one record of a specific kind.",
        "resolution": "Add the required record kind, or use a profile that matches the workspace scope.",
    },
    "readiness.required": {
        "title": "Readiness field missing",
        "severity": "warning",
        "description": "A readiness gate requires a field that is missing or empty.",
        "resolution": "Add the required field or adjust the relevant pack readiness gate.",
    },
    "readiness.min_items": {
        "title": "Readiness list too small",
        "severity": "warning",
        "description": "A readiness gate requires a list field to contain at least a minimum number of items.",
        "resolution": "Add the required items to the record.",
    },
    "record.id.duplicate": {
        "title": "Duplicate record ID",
        "severity": "error",
        "description": "Two records use the same ID.",
        "resolution": "Give each record a unique stable ID.",
    },
    "record.id.missing": {
        "title": "Missing record ID",
        "severity": "error",
        "description": "A record does not define a string ID.",
        "resolution": "Add an id field that matches the VeritySpec ID pattern.",
    },
    "record.kind.missing": {
        "title": "Missing record kind",
        "severity": "error",
        "description": "A record does not define a string kind.",
        "resolution": "Add a kind field declared by one of the loaded packs.",
    },
    "record.kind.unknown": {
        "title": "Unknown record kind",
        "severity": "error",
        "description": "A record uses a kind not declared by the loaded packs.",
        "resolution": "Load the pack that declares the kind or change the record kind.",
    },
    "reference.deprecated": {
        "title": "Deprecated reference",
        "severity": "warning",
        "description": "A record references another record marked deprecated.",
        "resolution": "Move the reference to the replacement record or acknowledge it before release.",
    },
    "reference.disallowed": {
        "title": "Disallowed reference relationship",
        "severity": "error",
        "description": "The source kind, relationship, and target kind combination is not allowed by loaded pack rules.",
        "resolution": "Use an allowed relationship or add a pack rule that explicitly permits it.",
    },
    "reference.missing": {
        "title": "Missing reference target",
        "severity": "error",
        "description": "A reference points to a record ID that does not exist in the workspace.",
        "resolution": "Create the target record or update the reference target.",
    },
    "reference.removed": {
        "title": "Removed reference target",
        "severity": "error",
        "description": "A record references another record marked removed.",
        "resolution": "Remove the reference or point it to an active replacement.",
    },
    "schema.unused": {
        "title": "Unused schema",
        "severity": "warning",
        "description": "A schema record has no incoming references.",
        "resolution": "Reference the schema from a record or remove it.",
    },
    "schema.validation": {
        "title": "Schema validation failure",
        "severity": "error",
        "description": "A record does not satisfy the JSON Schema for its kind.",
        "resolution": "Update the record to match its pack schema.",
    },
    "security.control.critical_unverified": {
        "title": "Critical security control not verified",
        "severity": "warning",
        "description": "A critical security control is release-relevant but is not marked as verified.",
        "resolution": "Set coverage to verified and provide a verification method other than not-verified with evidence.",
    },
    "security.control.evidence_stale": {
        "title": "Security verification evidence stale",
        "severity": "warning",
        "description": "A security control declares a review cadence, but its verification date is missing or older than that cadence.",
        "resolution": "Update verification.lastVerified after reviewing the evidence, or adjust verification.reviewCadenceDays to the accepted cadence.",
    },
    "accessibility.claim.critical_unverified": {
        "title": "Critical accessibility claim not verified",
        "severity": "warning",
        "description": "A critical accessibility claim is release-relevant but is not marked as verified.",
        "resolution": "Set coverage to verified and provide a verification method other than not-verified with evidence.",
    },
    "compliance.mapping.reviewed_unverified": {
        "title": "Reviewed compliance mapping not verified",
        "severity": "warning",
        "description": "A compliance mapping marked reviewed is missing verification evidence.",
        "resolution": "Use a verification method other than not-verified and provide evidence, or lower coverage until review is complete.",
    },
    "deployment.target.production_release_controls_missing": {
        "title": "Production deployment controls missing",
        "severity": "warning",
        "description": "A production deployment target is missing required release approval, rollback, health-check, security, observability, compliance, or release evidence links.",
        "resolution": "Require release approval, declare a rollback plan, add a production healthCheckUrl, and link security controls, observability dashboards, compliance mappings, and release evidence records.",
    },
    "dependency.alias.duplicate": {
        "title": "Duplicate workspace dependency alias",
        "severity": "error",
        "description": "A workspace declares the same dependency alias more than once.",
        "resolution": "Give each dependency declaration a unique alias.",
    },
    "dependency.alias.unknown": {
        "title": "Unknown workspace dependency alias",
        "severity": "error",
        "description": "A reference uses an alias-qualified dependency target, but the workspace does not declare that dependency alias.",
        "resolution": "Declare the dependency alias in verityspec.json or update the reference target.",
    },
    "dependency.declaration.invalid": {
        "title": "Invalid workspace dependency declaration",
        "severity": "error",
        "description": "A workspace dependency declaration is missing required local dependency fields or uses an invalid shape.",
        "resolution": "Declare dependency id, alias, source, optional version, and readonly mode using the supported local dependency shape.",
    },
    "dependency.exports.invalid": {
        "title": "Invalid dependency exports",
        "severity": "error",
        "description": "A dependency workspace exports list is not an array of record ID strings.",
        "resolution": "Set exports to an array of record IDs that the dependency intentionally exposes to consumers.",
    },
    "dependency.id.mismatch": {
        "title": "Workspace dependency ID mismatch",
        "severity": "error",
        "description": "A declared dependency ID does not match the workspace loaded from the dependency source path.",
        "resolution": "Update the dependency id or source path so the declaration and loaded workspace agree.",
    },
    "dependency.load.failed": {
        "title": "Workspace dependency failed to load",
        "severity": "error",
        "description": "A declared local workspace dependency could not be parsed or loaded.",
        "resolution": "Fix the dependency workspace files or point source at a valid VeritySpec workspace.",
    },
    "dependency.mode.unsupported": {
        "title": "Unsupported workspace dependency mode",
        "severity": "error",
        "description": "A workspace dependency declares a mode other than readonly.",
        "resolution": "Set dependency mode to readonly for the local dependency prototype.",
    },
    "dependency.reference.missing": {
        "title": "Missing workspace dependency reference target",
        "severity": "error",
        "description": "A dependency-qualified reference points to a record ID that does not exist in the dependency workspace.",
        "resolution": "Create and export the target record in the dependency workspace or update the reference.",
    },
    "dependency.reference.not_exported": {
        "title": "Workspace dependency reference not exported",
        "severity": "error",
        "description": "A dependency-qualified reference points to a record that exists but is not exported by the dependency workspace.",
        "resolution": "Add the target record ID to the dependency workspace exports list or reference an exported record.",
    },
    "dependency.source.missing": {
        "title": "Missing workspace dependency source",
        "severity": "error",
        "description": "A local workspace dependency source path does not exist.",
        "resolution": "Create the dependency workspace at the source path or update the dependency declaration.",
    },
    "dependency.version.missing": {
        "title": "Missing workspace dependency version",
        "severity": "error",
        "description": "A dependency declaration includes a version constraint but the loaded dependency workspace has no version.",
        "resolution": "Add a version to the dependency workspace manifest or remove the version constraint.",
    },
    "dependency.version.unsatisfied": {
        "title": "Workspace dependency version unsatisfied",
        "severity": "error",
        "description": "A loaded dependency workspace version does not satisfy the consuming workspace dependency constraint.",
        "resolution": "Update the dependency source or version constraint so they agree.",
    },
    "workspace.dependencies.invalid": {
        "title": "Invalid workspace dependencies",
        "severity": "error",
        "description": "The workspace dependencies field is not an array.",
        "resolution": "Set dependencies to an array of local dependency declarations or remove the field.",
    },
    "workspace.packPaths.invalid": {
        "title": "Invalid workspace pack paths",
        "severity": "error",
        "description": "A v0.2.0 workspace declares packPaths, but it is not an array of strings.",
        "resolution": "Set packPaths to an array of local pack paths, or [] when no external packs are used.",
    },
    "workspace.packPaths.missing": {
        "title": "Missing workspace pack paths",
        "severity": "error",
        "description": "A v0.2.0 workspace must declare packPaths explicitly.",
        "resolution": "Run `verity migrate` or add `\"packPaths\": []` to verityspec.json.",
    },
    "workspace.version.future": {
        "title": "Future workspace version",
        "severity": "error",
        "description": "The workspace declares a specVersion newer than this VeritySpec CLI supports.",
        "resolution": "Install a newer VeritySpec CLI before validating or migrating the workspace.",
    },
    "workspace.version.invalid": {
        "title": "Invalid workspace version",
        "severity": "error",
        "description": "The workspace specVersion does not use vMAJOR.MINOR.PATCH format.",
        "resolution": "Set specVersion to a supported value such as v0.2.0.",
    },
    "workspace.version.missing": {
        "title": "Missing workspace version",
        "severity": "error",
        "description": "The workspace config does not declare a specVersion.",
        "resolution": "Run `verity migrate` or add a supported specVersion to verityspec.json.",
    },
    "workspace.version.unsupported": {
        "title": "Unsupported workspace version",
        "severity": "error",
        "description": "The workspace declares a version this VeritySpec CLI does not support.",
        "resolution": "Run `verity migrate` to produce a supported workspace version.",
    },
}


def explain_issue(code: str) -> dict[str, str] | None:
    return ISSUE_EXPLANATIONS.get(code)
